version: "3"

services:
  db:
    # https://github.com/docker-library/docs/tree/master/postgres
    # image: postgres:14.2-alpine
    # https://github.com/postgis/docker-postgis/
    image: postgis/postgis:14-3.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: waypoints

  api:
    build: ./api/
    # command: poetry --version
    # command: poetry run uvicorn src.main:app --host 0.0.0.0 --reload
    command: ./wait-for-postgres.sh poetry run uvicorn src.main:app --host 0.0.0.0 --reload
    ports:
      - 8000:8000
    volumes:
      - ./api/src:/home/src
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: waypoints
